### ISSUE TITLE
Implement card with polling station information

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/vot-romania#15]
As an user of the platform, when clicking on a polling station I want to see information about that polling station:
- the county and polling station number
- the address of the polling station
- the streets that are assigned to that polling station

Navigate the UX prototype to see the polling station information cards and the workflow:
https://www.figma.com/proto/pWnmAAJV0yv3xkX1wUbG6B/Vot-Romania-NEW?node-id=1%3A2&scaling=min-zoom

**Comment by gabrielionita** [comment]
I'd like to take this one

**Comment by RaduCStefanescu** [comment]
All yours @gabrielionita
