### ISSUE TITLE
Implement map pop up

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/vot-romania#20]
After searching for a polling station, an user can see on a map the pins for the polling station location. We need ti display for each pin on the map a pop up with the information about the polling stations at that location.

![Rectangle 68](https://user-images.githubusercontent.com/15039873/82723687-4ce2f500-9cd9-11ea-8408-6fe836bdf0de.png)

**Comment by CristianCpi** [comment]
I would like to help on this one

**Comment by RaduCStefanescu** [comment]
All your @CristianCpi
