### ISSUE TITLE
Implement admin page

### ISSUE THREAD

**Issue by idormenco** [code4romania/vot-romania#5]
- add a web page `/admin` where users can edit/add static texts for all pages

- add a WYSIWYG/Rich Text editor example: [Example](https://www.npmjs.com/package/@kolkov/angular-editor)

The editor should contain the following editable content:
- Hero content: "Pe xx au loc alegeri..."
- Procedure content: "Conform legislației electorale..."
- Option title
- Option content

**Comment by daryne77** [comment]
🙋‍♀️

**Comment by RaduCStefanescu** [comment]
All yours @daryne77
