### ISSUE TITLE
Create Despre proiect page

### ISSUE THREAD

**Issue by idormenco** [code4romania/vot-romania#61]
please create a static page  `Despre proiect` see design in  [Figma ](https://www.figma.com/file/pWnmAAJV0yv3xkX1wUbG6B/Re-Vot-Romania-NEW?node-id=172%3A2) 
Text is static and should not be editable from admin page.
Please add a button in nav bar near language dropdown

**Comment by gheorghelupu17** [comment]
i will pick this
